name: ssd_tutorial
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.15.0
  - scipy>=1.4.0
  - scikit-learn
  - pandas
  - matplotlib
  - ipython
  - jupyter
  - pytorch
  - tqdm